### ISSUE TITLE
JSONObject["author"] not found - reddit 

### ISSUE THREAD

**Issue by mykeehu** [borderline232/ripme#3]
* Ripme version: 1.7.97
* Java version: latest
* Operating system: Win10

* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/user/freshbeaver (18+ site!)

* I've got 'JSONObject["author"] not found' error when ripping with your version. I tested with "mobile-buggy" ripme-2.0.1-14-f8ee4d01 version from here: https://github.com/ripmeapp2/ripme/releases and with this hasn't any problem, run perfectly.
* Please check your version, what is problem there!

**Comment by borderline232** [comment]
Fix will be up soon, thanks for pointing it out.

**Comment by borderline232** [comment]
Alright, fixed made some couple other minor changes as well. New release is up, hope this solves your issue. Going to close this issue for now.
